version: '3.8'

services:

  customermicroservice:
    build: .
    image: guidi/customermicroservice:latest
    restart: always
    networks:
      - network
    depends_on:
      - mongo
    ports:
      - 9000:9000
    environment:
      API__NAME: "Challenge API"
      API__VERSION: "v1"

  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - network
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  network: