version: "3.8"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
  customermicroservice:
    build: .
    image: guidi/customermicroservice:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8080:8080