version: '3.8'
services:

  customermicroservice:
    build: .
    image: customermicroservice:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 9000:8080
    environment:
      JAVA_OPTS: '-Ddebug -Xmx128m' #For debugging purposes
      MONGO_AUTHENTICATION_DATABASE: admin
      MONGO_DATABASE: customermicroservice
      MONGO_HOST: mongodb
      MONGO_PASSWORD: example
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      SERVER_PORT: 8080

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 #Not necessary on the final release
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
